# =============================================================================
# PRODUCT SERVICE KONG CONFIGURATION
# =============================================================================
# This file defines Kong routes, plugins, and configuration for the product service
# Drop this file in kong-services/ directory to automatically configure Kong

name: product-service
url: http://product-service.farmers-market.svc.cluster.local:80

routes:
  # Main V1 API route
  - name: product-service-v1-route
    paths:
      - /v1/products
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    strip_path: false
    preserve_host: false

plugins:
  # CORS Plugin
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  # Rate Limiting Plugin (higher limits for product browsing)
  - name: rate-limiting
    config:
      minute: 200
      hour: 2000
      policy: local

  # Request Transformer Plugin
  - name: request-transformer
    config:
      add:
        headers:
          - "X-Forwarded-By:Kong"
          - "X-Service:product-service"

  # Optional: Response Transformer (add product metadata)
  # - name: response-transformer
  #   config:
  #     add:
  #       headers:
  #         - "X-Product-API-Version:v1"
